<a href="https://colab.research.google.com/github/Ferdaus71/ML_Lab-performance/blob/main/AI_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array = np.array([
    [5, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
result = array[:-1] * array[1:]

print("Original array:")
print(array)
print("\nperform element-wise multiplications between each pair of consecutive rows:")
print(result)

Original array:
[[ 5  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

perform element-wise multiplications between each pair of consecutive rows:
[[ 30  14  24  36  50]
 [ 66  84 104 126 150]
 [176 204 234 266 300]]


In [ ]:
import numpy as np

N = 5
heights = np.random.uniform(1.5, 2.0, N)
weights = np.random.uniform(50, 100, N)
bmi = weights / (heights ** 2)

filtered_data = [
    {"height": h, "weight": w, "bmi": b}
    for h, w, b in zip(heights[bmi > 25], weights[bmi > 25], bmi[bmi > 25])
]

print("People with BMI > 25:")
for person in filtered_data:
    print(f"Height: {person['height']:.2f}m, Weight: {person['weight']:.2f}kg, BMI: {person['bmi']:.2f}")

People with BMI > 25:
Height: 1.83m, Weight: 85.32kg, BMI: 25.54
Height: 1.79m, Weight: 90.72kg, BMI: 28.37
Height: 1.58m, Weight: 87.02kg, BMI: 34.93
